version: '3'
services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      # POSTGRES_DB: travel_planning
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    networks:
      - netmain

  laravel:
    image: php:8.1-fpm
    container_name: backend
    working_dir: /var/www/backend
    volumes:
      - ./api:/var/www/backend
    entrypoint: ['php', 'artisan']
    command: ['serve', '--host=0.0.0.0']
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - netmain

  frontend:
    image: node:14
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '8081:8081'
    working_dir: /app
    volumes:
      - ./app:/app
    command: 'yarn start'
    networks:
      - netmain

networks:
  netmain:
