name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Composer.lock
      working-directory: ./api
      run: composer update --lock

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      working-directory: ./api
      run: composer install --prefer-dist --no-progress

    - name: Install PHPUnit
      working-directory: ./api
      run: composer require --dev phpunit/phpunit

    - name: Debug Info
      run: |
        php -v
        ./vendor/bin/phpunit --version  

    - name: Run PHPUnit Tests
      working-directory: ./api/tests
      run: composer test

    # Qualidade de Código
    #- name: Run PHP CodeSniffer
     # run: vendor/bin/phpcs
